# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: saad489254@gmial.com
author_name: SaadAbdullah72
contract_name: agr
deployment_language: python
preset_name: production
project_name: agr-contracts

